\connect tada

DROP TABLE todos;
DROP TABLE cities;

CREATE TABLE IF NOT EXISTS todos (
  id BIGSERIAL PRIMARY KEY,
  notes VARCHAR(1024),
  complete_status BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS cities (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(255),
  img VARCHAR(255),
  zipcode INTEGER
);